routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});

Route::post('/login', [LoginController::class, 'login']);
Route::get('/logout', [LoginController::class, 'logout']);
Route::middleware('auth:sanctum')->group(function () {
    Route::resource('/category', CategoryController::class);
    Route::resource('/product', ProductController::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property string $name
 * @property string $description
 * @property int $category_id
 * @property int $price
 */
class Product extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'products';

    protected $fillable = [
        'name',
        'description',
        'category_id',
        'price'
    ];

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function images(): HasMany
    {
        return $this->hasMany(ProductImages::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateOrEditProductRequest;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(Request $request)
    {
        $product = Product::query();

        $selectedCategory = '';

        if ($request->get('category_id')) {
            $category_id = $request->get('category_id');
            $product->where('category_id', $category_id);
            $selectedCategory = $category_id;
        }

        if ($request->get('name')) {
            $name = $request->get('name');
            $product->where('name', 'like', '%' .$name . '%');
        }

        if ($request->get('price_min')) {
            $price_min = $request->get('price_min');
            $product->where('price', '=<', $price_min);
        }

        if ($request->get('price_max')) {
            $price_max = $request->get('price_max');
            $product->where('price', '>=', $price_max);
        }

        return view('product.index', [
            'products' => $product->get(),
            'categories' => Category::all(),
            'selectedCategory' => $selectedCategory
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateOrEditProductRequest $request
     * @return RedirectResponse
     */
    public function store(CreateOrEditProductRequest $request): RedirectResponse
    {
        try {
            $product = new Product();
            $this->createOrUpdate($request, $product);
            return back();
        } catch (\Exception $exception) {
            return back()->withErrors(['errors' => $exception->getMessage()]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CreateOrEditProductRequest $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(CreateOrEditProductRequest $request, int $id): RedirectResponse
    {
        try {
            $product = Product::where('id', $id)->first();
            $this->createOrUpdate($request, $product);
            return back();
        } catch (\Exception $exception) {
            return back()->withErrors(['errors' => $exception->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse|void
     */
    public function destroy(int $id)
    {
        try {
            $product = Product::where('id', $id)->first();
            $product->images()->delete();
            $product->delete();
            return back();
        } catch (\Exception $exception) {
            return back()->withErrors(['errors' => $exception->getMessage()]);
        }
    }

    public function createOrUpdate(CreateOrEditProductRequest $request, Product $product) {
        DB::transaction(function () use ($request, $product) {
            $product->name = $request->get('name');
            $product->description = $request->get('description');
            $product->price = $request->get('price');
            $product->category_id = $request->get('category_id');

            $product->save();

            $product->images()->delete();
            $files = $request->allFiles();
            foreach ($files as $file) {
                Storage::disk('local')->put('public/' . $file[0]->getClientOriginalName(), file_get_contents($file[0]));
                $product->images()->create([
                    'path' => $file[0]->getClientOriginalName()
                ]);
            }

            if (!isset($product->id)) {
                throw new \Exception('Product not created');
            }

            if (!isset($product->images()->first()->id)) {
                throw new \Exception('Image not created');
            }
        });
    }
}

resources/views/product/index.blade.php
@extends('home')
@section('content')

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Create Product
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="/product" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="product-name" class="col-form-label">Name:</label>
                            <input type="text" name="name" class="form-control" id="product-name">
                        </div>
                        <div class="form-group">
                            <label for="product-description" class="col-form-label">Description:</label>
                            <input type="text" name="description" class="form-control" id="product-description">
                        </div>
                        <div class="form-group">
                            <label for="product-price" class="col-form-label">Price:</label>
                            <input type="number" name="price" class="form-control" id="product-price">
                        </div>
                        <div class="form-group">
                            <label for="product-images" class="col-form-label">Images:</label>
                            <input type="file" class="form-control" name="images[]" id="product-images" multiple />
                        </div>
                        <div class="form-group">
                            <select class="form-control" name="category_id" id="category_id">
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}" @selected($selectedCategory == $category->id)>
                                        {{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div>
        <form action="/product" method="get">
            <div class="input-group">
                <div class="form-outline d-inline">
                    <input type="search" name="name" id="form1" class="form-control" />
                    <label class="form-label" for="form1">Name</label>
                </div>
            </div>
            <div class="input-group">
                <div class="form-outline  d-inline">
                    <select class="form-control" name="category_id" id="category_id">
                        @foreach ($categories as $category)
                            <option value="{{ $category->id }}" selected='{{$selectedCategory == $category->id}}'>
                                {{ $category->name }}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="input-group">
                <div class="form-outline d-inline">
                    <label for="product-price-min" class="col-form-label">Price Min:</label>
                    <input type="number" name="price_min" class="form-control" id="product-price-min">
                </div>
            </div>
            <div class="input-group">
                <div class="form-outline d-inline">
                    <label for="product-price-max" class="col-form-label">Price Max:</label>
                    <input type="number" name="price_max" class="form-control" id="product-price-max">
                </div>
            </div>
            <button type="submit" class="btn btn-outline-primary">Search</button>

        </form>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Price</th>
            <th scope="col">Images</th>
        </tr>
        </thead>
        <tbody>
        @foreach($products as $product)
            <tr>
                <th scope="row">{{$product->id}}</th>
                <td>
                    {{$product->name}}
                </td>
                <td>
                    {{$product->description}}
                </td>
                <td>
                    {{$product->price}}
                </td>
                <td>
                    @foreach($product->images as $image)
                        <img src="{{url('storage/' . $image->path)}}">
                    @endforeach
                </td>
                <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalProduct-{{$product->id}}">
                        Edit Product
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModalProduct-{{$product->id}}" tabindex="-1" aria-labelledby="exampleModalProductLabel-{{$product->id}}" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <form action="{{route('product.update', ['product' => $product])}}" method="POST">
                                    @csrf
                                    @method('PUT')
                                    <div class="modal-body">
                                        <input type="hidden" id="_token" value="{{csrf_token()}}">
                                        <div class="form-group">
                                            <label for="product-name" class="col-form-label">Name:</label>
                                            <input type="text" name="name" class="form-control" id="product-{{$product->id}}-name" value="{{$product->name}}">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </td>

                <td>
                    <div>
                        <form action="{{route('product.destroy', ['product' => $product])}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-primary">
                                Delete Product
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

@endsection