routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login');
});

Route::post('/login', [LoginController::class, 'login']);
Route::get('/logout', [LoginController::class, 'logout']);
Route::middleware('auth:sanctum')->group(function () {
    Route::resource('/category', CategoryController::class);
    Route::resource('/product', ProductController::class);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property string $name
 */
class Category extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'categories';

    protected $fillable = [
        'name'
    ];

    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateOrEditCategoryRequest;
use App\Models\Category;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Redirect;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $categories = Category::all();

        return view('category.index', [
            'categories' => $categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateOrEditCategoryRequest $request
     * @return RedirectResponse
     */
    public function store(CreateOrEditCategoryRequest $request): RedirectResponse
    {
        $category = new Category();
        $category->name = $request->get('name');
        $category->save();

        return Redirect::route('category.show', ['category' => $category]);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function show(int $id)
    {
        $category = Category::where('id', $id)->first();

        return view('category.category', ['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CreateOrEditCategoryRequest $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(CreateOrEditCategoryRequest $request, int $id): RedirectResponse
    {
        $category = Category::where('id', $id)->first();

        $category->name = $request->get('name');
        $category->save();

        return Redirect::route('category.show', ['category' => $category]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     */
    public function destroy(int $id): RedirectResponse
    {
        try {
            Category::destroy($id);
            return Redirect::route('category.index');
        } catch (\Exception $exception) {
            return back()->withErrors([
                'message' => $exception->getMessage()
            ]);
        }
    }
}

resources/views/category/category.blade.php
@extends('home')
@section('content')

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Create Product
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="/product" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="product-name" class="col-form-label">Name:</label>
                            <input type="text" name="name" class="form-control" id="product-name">
                        </div>
                        <div class="form-group">
                            <label for="product-description" class="col-form-label">Description:</label>
                            <input type="text" name="description" class="form-control" id="product-description">
                        </div>
                        <div class="form-group">
                            <label for="product-price" class="col-form-label">Price:</label>
                            <input type="number" name="price" class="form-control" id="product-price">
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
        </tr>
        </thead>
        <tbody>
        @foreach($category->products as $product)
            <tr>
                <th scope="row">{{$product->id}}</th>
                <td>
                    <a href="{{route('product.show', ['product' => $product])}}">
                        {{$product->name}}
                    </a>
                </td>
                <td>
                    <div>
                        <form action="{{route('product.destroy', ['product' => $product])}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-primary">
                                Delete Product
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

@endsection

resources/views/category/index.blade.php
@extends('home')
@section('content')

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Create Category
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="/category" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="category-name" class="col-form-label">Name:</label>
                            <input type="text" name="name" class="form-control" id="category-name">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
        </tr>
        </thead>
        <tbody>
        @foreach($categories as $category)
            <tr>
                <th scope="row">{{$category->id}}</th>
                <td>
                    <a href="{{route('product.index', ['category_id' => $category->id])}}">
                        {{$category->name}}
                    </a>
                </td>

                <td>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCategory-{{$category->id}}">
                        Edit Category
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModalCategory-{{$category->id}}" tabindex="-1" aria-labelledby="exampleModalCategoryLabel-{{$category->id}}" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <form action="{{route('category.update', ['category' => $category])}}" method="POST">
                                    @csrf
                                    @method('PUT')
                                    <div class="modal-body">
                                        <input type="hidden" id="_token" value="{{csrf_token()}}">
                                        <div class="form-group">
                                            <label for="category-name" class="col-form-label">Name:</label>
                                            <input type="text" name="name" class="form-control" id="category-{{$category->id}}-name" value="{{$category->name}}">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </td>

                <td>
                    <div>
                        <form action="{{route('category.destroy', ['category' => $category])}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-primary">
                                Delete Category
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

@endsection